# nginx proxy address - http://172.17.0.1:59071

name: rocketchat
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  server:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    container_name: rocketchat-server
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      PORT: 3000
      ROOT_URL: https://${BASE_HOST_NAME:-$HOSTNAME}.${BASE_DOMAIN_NAME:-example.com}
      MONGO_URL: mongodb://rocketchat-db:27017/rocketchat?replicaSet=rs0
      MONGO_OPLOG_URL: mongodb://rocketchat-db:27017/local?replicaSet=rs0
      CONTAINER_NAME: rocketchat-server
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - 172.17.0.1:59071:3000
    volumes:
      - './volumes/data/rocketchat/uploads:/app/uploads'
    depends_on:
      - db
    networks:
      - rocketchat
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://rocketchat-server:3000'
      - 'cloudflare.hostname=rocketchat.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.rocketchat-server.entrypoints=http'
      - 'traefik.http.routers.rocketchat-server-secure.tls=true'
      - 'traefik.http.routers.rocketchat-server.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.rocketchat-server-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.rocketchat-server.middlewares=rocketchat-server-https-redirect'
      - 'traefik.http.routers.rocketchat-server-secure.entrypoints=https'
      - 'traefik.http.routers.rocketchat-server-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.rocketchat-server-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.rocketchat-server-secure.service=rocketchat-server'
      - 'traefik.http.services.rocketchat-server.loadbalancer.server.port=3000'

  db:
    image: docker.io/bitnami/mongodb:latest
    container_name: rocketchat-db
    hostname: rocketchat-db
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      MONGODB_PORT_NUMBER: 27017
      ALLOW_EMPTY_PASSWORD: yes
      MONGODB_ENABLE_JOURNAL: true
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 7017
      MONGODB_ADVERTISED_HOSTNAME: rocketchat-db
      MONGODB_INITIAL_PRIMARY_HOST: rocketchat-db
      CONTAINER_NAME: rocketchat-db
    volumes:
      - './volumes/data/db/mongodb/rocketchat:/bitnami/mongodb'
    networks:
      - rocketchat

networks:
  rocketchat:
    name: rocketchat
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
